<?php

namespace Recranet\OTA\Type;

/**
 * Class representing SeatMapQueryType
 *
 * Object to hold criteria used to generate one or more seat maps.
 * XSD Type: SeatMapQueryType
 */
class SeatMapQueryType
{
    /**
     * Indicates smoking is allowed when true and is not allowed when false.
     *
     *  false
     *
     * @var bool $smokingAllowed
     */
    private $smokingAllowed = null;

    /**
     * The calculated number of required seats, e.g.: 0 for Infant On Lap, 1 for Normal Passenger and 2 for Oversized Passenger. This may be used to determine if two seats need to be together.
     *
     * @var int $totalReqSeatQty
     */
    private $totalReqSeatQty = null;

    /**
     * If true, this is a seat re-accommodation request. In this scenario, two instances of DetailedInfo should be used, one for the original equipment and one for the changed equipment.
     *
     * @var bool $changeInd
     */
    private $changeInd = null;

    /**
     * Flight information, including flight number, airline, arrival, departure, origin/destination and flight segment(s).
     *
     * @var \Recranet\OTA\Type\SeatMapQueryType\FlightInfoAType[] $flightInfo
     */
    private $flightInfo = [
        
    ];

    /**
     * One or more unique aircraft equipment types to generate a seat map for.
     *
     * @var \Recranet\OTA\Type\EquipmentType[] $equipment
     */
    private $equipment = [
        
    ];

    /**
     * Booking reference (PNR) information if the seat map is being generated by PNR. Note that travelers with associated PNR(s) are defined here.
     *
     * @var \Recranet\OTA\Type\BookingReferenceType[] $bookingReferenceID
     */
    private $bookingReferenceID = [
        
    ];

    /**
     * Cabin classes to be included or excluded from the seat map(s).
     *
     * @var \Recranet\OTA\Type\SeatMapQueryType\CabinClassAType[] $cabinClass
     */
    private $cabinClass = [
        
    ];

    /**
     * An extensible list of seat features to be included in the seat map. Select an item from the list or use the Other_ list value and enter a seat feature in the @extension attribute that is known to trading partners.
     *
     * @var \Recranet\OTA\Type\SeatFeaturesType[] $features
     */
    private $features = [
        
    ];

    /**
     * Known or specifically requested seat information.
     *
     * @var \Recranet\OTA\Type\SeatMapQueryType\SpecificSeatInfoAType[] $specificSeatInfo
     */
    private $specificSeatInfo = [
        
    ];

    /**
     * Object to hold the seat details that is to be requested.
     *
     * @var \Recranet\OTA\Type\SeatMapQueryType\SeatDetailsAType $seatDetails
     */
    private $seatDetails = null;

    /**
     * An extensible list of seat status types to be included in the seat map. Select an existing value from the list or use "Other_" and the @extension attribute to add a new value known between trading partners.
     *
     * @var \Recranet\OTA\Type\StatusType[] $status
     */
    private $status = [
        
    ];

    /**
     * Details about travelers not associated with a booking reference (PNR.)
     *
     * @var \Recranet\OTA\Type\TravelerInfoType[] $traveler
     */
    private $traveler = [
        
    ];

    /**
     * Zones to be included or excluded from the seat map(s).
     *
     * @var \Recranet\OTA\Type\SeatZoneQueryType[] $zone
     */
    private $zone = [
        
    ];

    /**
     * @var \Recranet\OTA\Type\TPAExtensions $tPAExtensions
     */
    private $tPAExtensions = null;

    /**
     * Gets as smokingAllowed
     *
     * Indicates smoking is allowed when true and is not allowed when false.
     *
     *  false
     *
     * @return bool
     */
    public function getSmokingAllowed()
    {
        return $this->smokingAllowed;
    }

    /**
     * Sets a new smokingAllowed
     *
     * Indicates smoking is allowed when true and is not allowed when false.
     *
     *  false
     *
     * @param bool $smokingAllowed
     * @return self
     */
    public function setSmokingAllowed($smokingAllowed)
    {
        $this->smokingAllowed = $smokingAllowed;
        return $this;
    }

    /**
     * Gets as totalReqSeatQty
     *
     * The calculated number of required seats, e.g.: 0 for Infant On Lap, 1 for Normal Passenger and 2 for Oversized Passenger. This may be used to determine if two seats need to be together.
     *
     * @return int
     */
    public function getTotalReqSeatQty()
    {
        return $this->totalReqSeatQty;
    }

    /**
     * Sets a new totalReqSeatQty
     *
     * The calculated number of required seats, e.g.: 0 for Infant On Lap, 1 for Normal Passenger and 2 for Oversized Passenger. This may be used to determine if two seats need to be together.
     *
     * @param int $totalReqSeatQty
     * @return self
     */
    public function setTotalReqSeatQty($totalReqSeatQty)
    {
        $this->totalReqSeatQty = $totalReqSeatQty;
        return $this;
    }

    /**
     * Gets as changeInd
     *
     * If true, this is a seat re-accommodation request. In this scenario, two instances of DetailedInfo should be used, one for the original equipment and one for the changed equipment.
     *
     * @return bool
     */
    public function getChangeInd()
    {
        return $this->changeInd;
    }

    /**
     * Sets a new changeInd
     *
     * If true, this is a seat re-accommodation request. In this scenario, two instances of DetailedInfo should be used, one for the original equipment and one for the changed equipment.
     *
     * @param bool $changeInd
     * @return self
     */
    public function setChangeInd($changeInd)
    {
        $this->changeInd = $changeInd;
        return $this;
    }

    /**
     * Adds as flightInfo
     *
     * Flight information, including flight number, airline, arrival, departure, origin/destination and flight segment(s).
     *
     * @return self
     * @param \Recranet\OTA\Type\SeatMapQueryType\FlightInfoAType $flightInfo
     */
    public function addToFlightInfo(\Recranet\OTA\Type\SeatMapQueryType\FlightInfoAType $flightInfo)
    {
        $this->flightInfo[] = $flightInfo;
        return $this;
    }

    /**
     * isset flightInfo
     *
     * Flight information, including flight number, airline, arrival, departure, origin/destination and flight segment(s).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetFlightInfo($index)
    {
        return isset($this->flightInfo[$index]);
    }

    /**
     * unset flightInfo
     *
     * Flight information, including flight number, airline, arrival, departure, origin/destination and flight segment(s).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetFlightInfo($index)
    {
        unset($this->flightInfo[$index]);
    }

    /**
     * Gets as flightInfo
     *
     * Flight information, including flight number, airline, arrival, departure, origin/destination and flight segment(s).
     *
     * @return \Recranet\OTA\Type\SeatMapQueryType\FlightInfoAType[]
     */
    public function getFlightInfo()
    {
        return $this->flightInfo;
    }

    /**
     * Sets a new flightInfo
     *
     * Flight information, including flight number, airline, arrival, departure, origin/destination and flight segment(s).
     *
     * @param \Recranet\OTA\Type\SeatMapQueryType\FlightInfoAType[] $flightInfo
     * @return self
     */
    public function setFlightInfo(array $flightInfo)
    {
        $this->flightInfo = $flightInfo;
        return $this;
    }

    /**
     * Adds as equipment
     *
     * One or more unique aircraft equipment types to generate a seat map for.
     *
     * @return self
     * @param \Recranet\OTA\Type\EquipmentType $equipment
     */
    public function addToEquipment(\Recranet\OTA\Type\EquipmentType $equipment)
    {
        $this->equipment[] = $equipment;
        return $this;
    }

    /**
     * isset equipment
     *
     * One or more unique aircraft equipment types to generate a seat map for.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetEquipment($index)
    {
        return isset($this->equipment[$index]);
    }

    /**
     * unset equipment
     *
     * One or more unique aircraft equipment types to generate a seat map for.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetEquipment($index)
    {
        unset($this->equipment[$index]);
    }

    /**
     * Gets as equipment
     *
     * One or more unique aircraft equipment types to generate a seat map for.
     *
     * @return \Recranet\OTA\Type\EquipmentType[]
     */
    public function getEquipment()
    {
        return $this->equipment;
    }

    /**
     * Sets a new equipment
     *
     * One or more unique aircraft equipment types to generate a seat map for.
     *
     * @param \Recranet\OTA\Type\EquipmentType[] $equipment
     * @return self
     */
    public function setEquipment(array $equipment = null)
    {
        $this->equipment = $equipment;
        return $this;
    }

    /**
     * Adds as bookingReferenceID
     *
     * Booking reference (PNR) information if the seat map is being generated by PNR. Note that travelers with associated PNR(s) are defined here.
     *
     * @return self
     * @param \Recranet\OTA\Type\BookingReferenceType $bookingReferenceID
     */
    public function addToBookingReferenceID(\Recranet\OTA\Type\BookingReferenceType $bookingReferenceID)
    {
        $this->bookingReferenceID[] = $bookingReferenceID;
        return $this;
    }

    /**
     * isset bookingReferenceID
     *
     * Booking reference (PNR) information if the seat map is being generated by PNR. Note that travelers with associated PNR(s) are defined here.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetBookingReferenceID($index)
    {
        return isset($this->bookingReferenceID[$index]);
    }

    /**
     * unset bookingReferenceID
     *
     * Booking reference (PNR) information if the seat map is being generated by PNR. Note that travelers with associated PNR(s) are defined here.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetBookingReferenceID($index)
    {
        unset($this->bookingReferenceID[$index]);
    }

    /**
     * Gets as bookingReferenceID
     *
     * Booking reference (PNR) information if the seat map is being generated by PNR. Note that travelers with associated PNR(s) are defined here.
     *
     * @return \Recranet\OTA\Type\BookingReferenceType[]
     */
    public function getBookingReferenceID()
    {
        return $this->bookingReferenceID;
    }

    /**
     * Sets a new bookingReferenceID
     *
     * Booking reference (PNR) information if the seat map is being generated by PNR. Note that travelers with associated PNR(s) are defined here.
     *
     * @param \Recranet\OTA\Type\BookingReferenceType[] $bookingReferenceID
     * @return self
     */
    public function setBookingReferenceID(array $bookingReferenceID = null)
    {
        $this->bookingReferenceID = $bookingReferenceID;
        return $this;
    }

    /**
     * Adds as cabinClass
     *
     * Cabin classes to be included or excluded from the seat map(s).
     *
     * @return self
     * @param \Recranet\OTA\Type\SeatMapQueryType\CabinClassAType $cabinClass
     */
    public function addToCabinClass(\Recranet\OTA\Type\SeatMapQueryType\CabinClassAType $cabinClass)
    {
        $this->cabinClass[] = $cabinClass;
        return $this;
    }

    /**
     * isset cabinClass
     *
     * Cabin classes to be included or excluded from the seat map(s).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetCabinClass($index)
    {
        return isset($this->cabinClass[$index]);
    }

    /**
     * unset cabinClass
     *
     * Cabin classes to be included or excluded from the seat map(s).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetCabinClass($index)
    {
        unset($this->cabinClass[$index]);
    }

    /**
     * Gets as cabinClass
     *
     * Cabin classes to be included or excluded from the seat map(s).
     *
     * @return \Recranet\OTA\Type\SeatMapQueryType\CabinClassAType[]
     */
    public function getCabinClass()
    {
        return $this->cabinClass;
    }

    /**
     * Sets a new cabinClass
     *
     * Cabin classes to be included or excluded from the seat map(s).
     *
     * @param \Recranet\OTA\Type\SeatMapQueryType\CabinClassAType[] $cabinClass
     * @return self
     */
    public function setCabinClass(array $cabinClass = null)
    {
        $this->cabinClass = $cabinClass;
        return $this;
    }

    /**
     * Adds as features
     *
     * An extensible list of seat features to be included in the seat map. Select an item from the list or use the Other_ list value and enter a seat feature in the @extension attribute that is known to trading partners.
     *
     * @return self
     * @param \Recranet\OTA\Type\SeatFeaturesType $features
     */
    public function addToFeatures(\Recranet\OTA\Type\SeatFeaturesType $features)
    {
        $this->features[] = $features;
        return $this;
    }

    /**
     * isset features
     *
     * An extensible list of seat features to be included in the seat map. Select an item from the list or use the Other_ list value and enter a seat feature in the @extension attribute that is known to trading partners.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetFeatures($index)
    {
        return isset($this->features[$index]);
    }

    /**
     * unset features
     *
     * An extensible list of seat features to be included in the seat map. Select an item from the list or use the Other_ list value and enter a seat feature in the @extension attribute that is known to trading partners.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetFeatures($index)
    {
        unset($this->features[$index]);
    }

    /**
     * Gets as features
     *
     * An extensible list of seat features to be included in the seat map. Select an item from the list or use the Other_ list value and enter a seat feature in the @extension attribute that is known to trading partners.
     *
     * @return \Recranet\OTA\Type\SeatFeaturesType[]
     */
    public function getFeatures()
    {
        return $this->features;
    }

    /**
     * Sets a new features
     *
     * An extensible list of seat features to be included in the seat map. Select an item from the list or use the Other_ list value and enter a seat feature in the @extension attribute that is known to trading partners.
     *
     * @param \Recranet\OTA\Type\SeatFeaturesType[] $features
     * @return self
     */
    public function setFeatures(array $features = null)
    {
        $this->features = $features;
        return $this;
    }

    /**
     * Adds as specificSeatInfo
     *
     * Known or specifically requested seat information.
     *
     * @return self
     * @param \Recranet\OTA\Type\SeatMapQueryType\SpecificSeatInfoAType $specificSeatInfo
     */
    public function addToSpecificSeatInfo(\Recranet\OTA\Type\SeatMapQueryType\SpecificSeatInfoAType $specificSeatInfo)
    {
        $this->specificSeatInfo[] = $specificSeatInfo;
        return $this;
    }

    /**
     * isset specificSeatInfo
     *
     * Known or specifically requested seat information.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetSpecificSeatInfo($index)
    {
        return isset($this->specificSeatInfo[$index]);
    }

    /**
     * unset specificSeatInfo
     *
     * Known or specifically requested seat information.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetSpecificSeatInfo($index)
    {
        unset($this->specificSeatInfo[$index]);
    }

    /**
     * Gets as specificSeatInfo
     *
     * Known or specifically requested seat information.
     *
     * @return \Recranet\OTA\Type\SeatMapQueryType\SpecificSeatInfoAType[]
     */
    public function getSpecificSeatInfo()
    {
        return $this->specificSeatInfo;
    }

    /**
     * Sets a new specificSeatInfo
     *
     * Known or specifically requested seat information.
     *
     * @param \Recranet\OTA\Type\SeatMapQueryType\SpecificSeatInfoAType[] $specificSeatInfo
     * @return self
     */
    public function setSpecificSeatInfo(array $specificSeatInfo = null)
    {
        $this->specificSeatInfo = $specificSeatInfo;
        return $this;
    }

    /**
     * Gets as seatDetails
     *
     * Object to hold the seat details that is to be requested.
     *
     * @return \Recranet\OTA\Type\SeatMapQueryType\SeatDetailsAType
     */
    public function getSeatDetails()
    {
        return $this->seatDetails;
    }

    /**
     * Sets a new seatDetails
     *
     * Object to hold the seat details that is to be requested.
     *
     * @param \Recranet\OTA\Type\SeatMapQueryType\SeatDetailsAType $seatDetails
     * @return self
     */
    public function setSeatDetails(?\Recranet\OTA\Type\SeatMapQueryType\SeatDetailsAType $seatDetails = null)
    {
        $this->seatDetails = $seatDetails;
        return $this;
    }

    /**
     * Adds as status
     *
     * An extensible list of seat status types to be included in the seat map. Select an existing value from the list or use "Other_" and the @extension attribute to add a new value known between trading partners.
     *
     * @return self
     * @param \Recranet\OTA\Type\StatusType $status
     */
    public function addToStatus(\Recranet\OTA\Type\StatusType $status)
    {
        $this->status[] = $status;
        return $this;
    }

    /**
     * isset status
     *
     * An extensible list of seat status types to be included in the seat map. Select an existing value from the list or use "Other_" and the @extension attribute to add a new value known between trading partners.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetStatus($index)
    {
        return isset($this->status[$index]);
    }

    /**
     * unset status
     *
     * An extensible list of seat status types to be included in the seat map. Select an existing value from the list or use "Other_" and the @extension attribute to add a new value known between trading partners.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetStatus($index)
    {
        unset($this->status[$index]);
    }

    /**
     * Gets as status
     *
     * An extensible list of seat status types to be included in the seat map. Select an existing value from the list or use "Other_" and the @extension attribute to add a new value known between trading partners.
     *
     * @return \Recranet\OTA\Type\StatusType[]
     */
    public function getStatus()
    {
        return $this->status;
    }

    /**
     * Sets a new status
     *
     * An extensible list of seat status types to be included in the seat map. Select an existing value from the list or use "Other_" and the @extension attribute to add a new value known between trading partners.
     *
     * @param \Recranet\OTA\Type\StatusType[] $status
     * @return self
     */
    public function setStatus(array $status = null)
    {
        $this->status = $status;
        return $this;
    }

    /**
     * Adds as traveler
     *
     * Details about travelers not associated with a booking reference (PNR.)
     *
     * @return self
     * @param \Recranet\OTA\Type\TravelerInfoType $traveler
     */
    public function addToTraveler(\Recranet\OTA\Type\TravelerInfoType $traveler)
    {
        $this->traveler[] = $traveler;
        return $this;
    }

    /**
     * isset traveler
     *
     * Details about travelers not associated with a booking reference (PNR.)
     *
     * @param int|string $index
     * @return bool
     */
    public function issetTraveler($index)
    {
        return isset($this->traveler[$index]);
    }

    /**
     * unset traveler
     *
     * Details about travelers not associated with a booking reference (PNR.)
     *
     * @param int|string $index
     * @return void
     */
    public function unsetTraveler($index)
    {
        unset($this->traveler[$index]);
    }

    /**
     * Gets as traveler
     *
     * Details about travelers not associated with a booking reference (PNR.)
     *
     * @return \Recranet\OTA\Type\TravelerInfoType[]
     */
    public function getTraveler()
    {
        return $this->traveler;
    }

    /**
     * Sets a new traveler
     *
     * Details about travelers not associated with a booking reference (PNR.)
     *
     * @param \Recranet\OTA\Type\TravelerInfoType[] $traveler
     * @return self
     */
    public function setTraveler(array $traveler = null)
    {
        $this->traveler = $traveler;
        return $this;
    }

    /**
     * Adds as zone
     *
     * Zones to be included or excluded from the seat map(s).
     *
     * @return self
     * @param \Recranet\OTA\Type\SeatZoneQueryType $zone
     */
    public function addToZone(\Recranet\OTA\Type\SeatZoneQueryType $zone)
    {
        $this->zone[] = $zone;
        return $this;
    }

    /**
     * isset zone
     *
     * Zones to be included or excluded from the seat map(s).
     *
     * @param int|string $index
     * @return bool
     */
    public function issetZone($index)
    {
        return isset($this->zone[$index]);
    }

    /**
     * unset zone
     *
     * Zones to be included or excluded from the seat map(s).
     *
     * @param int|string $index
     * @return void
     */
    public function unsetZone($index)
    {
        unset($this->zone[$index]);
    }

    /**
     * Gets as zone
     *
     * Zones to be included or excluded from the seat map(s).
     *
     * @return \Recranet\OTA\Type\SeatZoneQueryType[]
     */
    public function getZone()
    {
        return $this->zone;
    }

    /**
     * Sets a new zone
     *
     * Zones to be included or excluded from the seat map(s).
     *
     * @param \Recranet\OTA\Type\SeatZoneQueryType[] $zone
     * @return self
     */
    public function setZone(array $zone = null)
    {
        $this->zone = $zone;
        return $this;
    }

    /**
     * Gets as tPAExtensions
     *
     * @return \Recranet\OTA\Type\TPAExtensions
     */
    public function getTPAExtensions()
    {
        return $this->tPAExtensions;
    }

    /**
     * Sets a new tPAExtensions
     *
     * @param \Recranet\OTA\Type\TPAExtensions $tPAExtensions
     * @return self
     */
    public function setTPAExtensions(?\Recranet\OTA\Type\TPAExtensions $tPAExtensions = null)
    {
        $this->tPAExtensions = $tPAExtensions;
        return $this;
    }
}

