Recranet\OTA\Type\EnvironmentalImpactType\GeneralAType:
    properties:
        certification:
            -
                Valid: null
        environmental:
            -
                Valid: null
