Recranet\OTA\Type\EnvironmentalImpactType\RecyclingAType:
    properties:
        details:
            -
                Valid: null
        programDescription:
            -
                Valid: null
