Recranet\OTA\Type\EnvironmentalImpactType\EnergyAType:
    properties:
        energyGenerated:
            -
                GreaterThanOrEqual:
                    value: '1'
                    groups:
                        - xsd_rules
        usage:
            -
                Valid: null
        programDescription:
            -
                Valid: null
