Recranet\OTA\EnvironmentalImpactType\CarbonFootprintAType:
    properties:
        meetingEvent:
            -
                GreaterThanOrEqual:
                    value: '1'
                    groups:
                        - xsd_rules
        roomNight:
            -
                GreaterThanOrEqual:
                    value: '1'
                    groups:
                        - xsd_rules
        weatherNormalized:
            -
                GreaterThanOrEqual:
                    value: '1'
                    groups:
                        - xsd_rules
