Recranet\OTA\OTAHotelBookingRuleRS\OTAHotelBookingRuleRSAType\RuleMessageAType\StatusApplicationAType\RoomRatesAType\RoomRateAType:
    properties:
        currencyCode:
            -
                Regex:
                    pattern: '~[a-zA-Z]{3}~u'
                    groups:
                        - xsd_rules
        decimalPlaces:
            -
                GreaterThanOrEqual:
                    value: '0'
                    groups:
                        - xsd_rules
        rateTimeUnit:
            -
                Choice:
                    choices:
                        - Year
                        - Month
                        - Week
                        - Day
                        - Hour
                        - Second
                        - FullDuration
                        - Minute
                    groups:
                        - xsd_rules
        unitMultiplier:
            -
                GreaterThanOrEqual:
                    value: '1'
                    groups:
                        - xsd_rules
        rateDescription:
            -
                Valid: null
