Recranet\OTA\ProductDescriptionsType:
    properties:
        productDescription:
            -
                NotNull:
                    groups:
                        - xsd_rules
            -
                Valid: null
