Recranet\OTA\StatisticApplicationSetType\RevenueCategorySummariesAType:
    properties:
        revenueCategorySummary:
            -
                NotNull:
                    groups:
                        - xsd_rules
            -
                Valid: null
