Recranet\OTA\Type\StatisticApplicationSetType\CountCategorySummariesAType:
    properties:
        countCategorySummary:
            -
                NotNull:
                    groups:
                        - xsd_rules
            -
                Valid: null
