Recranet\OTA\Type\StatisticApplicationSetType\ReportSummariesAType:
    properties:
        reportSummary:
            -
                NotNull:
                    groups:
                        - xsd_rules
            -
                Valid: null
