Recranet\OTA\StatusApplicationControlType:
    properties:
        ratePlanType:
            -
                Regex:
                    pattern: '~[0-9A-Z]{1,3}(\.[A-Z]{3}(\.X){0,1}){0,1}~u'
                    groups:
                        - xsd_rules
        ratePlanCode:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '64'
                    groups:
                        - xsd_rules
        ratePlanID:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '64'
                    groups:
                        - xsd_rules
        promotionCode:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '32'
                    groups:
                        - xsd_rules
        ratePlanCategory:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '64'
                    groups:
                        - xsd_rules
        invCodeApplication:
            -
                Choice:
                    choices:
                        - DoesNotApply
                        - InvCode
                        - InvGroupingCode
                    groups:
                        - xsd_rules
        invCode:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '16'
                    groups:
                        - xsd_rules
        invType:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '16'
                    groups:
                        - xsd_rules
        invTypeCode:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '16'
                    groups:
                        - xsd_rules
        ratePlanCodeType:
            -
                Choice:
                    choices:
                        - DoesNotApply
                        - RatePlanCode
                        - RatePlanGroupingCode
                    groups:
                        - xsd_rules
        rateTier:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '64'
                    groups:
                        - xsd_rules
        invBlockCodeApply:
            -
                Choice:
                    choices:
                        - DoesNotApply
                        - BlockCode
                        - BlockGroupingCode
                    groups:
                        - xsd_rules
        invBlockCode:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '32'
                    groups:
                        - xsd_rules
        quoteID:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '32'
                    groups:
                        - xsd_rules
        subBlockCode:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '32'
                    groups:
                        - xsd_rules
        wingIdentifier:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '32'
                    groups:
                        - xsd_rules
        destinationSystemCodes:
            -
                Valid: null
