Recranet\OTA\Type\TrainIdentificationType:
    properties:
        trainNumber:
            -
                Length:
                    min: '1'
                    groups:
                        - xsd_rules
            -
                Length:
                    max: '8'
                    groups:
                        - xsd_rules
            -
                NotNull:
                    groups:
                        - xsd_rules
        networkCode:
            -
                Valid: null
