<?php

namespace Recranet\OTA\EnvironmentalImpactType;

/**
 * Class representing EnergyAType
 */
class EnergyAType
{
    /**
     * Energy efficient appliances indicator.
     * Example: true
     * Implementer: If true, the property uses energy efficient appliances (e.g. dish washers, washing machines, dryers).
     *
     * @var bool $efficientAppliancesInd
     */
    private $efficientAppliancesInd = null;

    /**
     * Energy efficient lighting used indicator.
     * Example: true
     * Implementer: If true, the property uses energy saving lighting facilities, such as energy-efficient LED fixtures.
     *
     * @var bool $efficientLightingInd
     */
    private $efficientLightingInd = null;

    /**
     * Combined heat and power units used indicator.
     * Example: true
     * Implementer: If true, the property uses combined heat and power units.
     *
     * @var bool $heatPowerCombInd
     */
    private $heatPowerCombInd = null;

    /**
     * Heat pumps used indicator.
     * Example: true
     * Implementer: If true, the property uses heat pumps.
     *
     * @var bool $heatPumpInd
     */
    private $heatPumpInd = null;

    /**
     * Power saving policy indicator.
     * Example: true
     * Implementer: If true, the property has a power saving policy.
     *
     * @var bool $powerSavingPolicyInd
     */
    private $powerSavingPolicyInd = null;

    /**
     * Solar energy used indicator.
     * Example: true
     * Implementer: If true, the property uses solar energy.
     *
     * @var bool $solarInd
     */
    private $solarInd = null;

    /**
     * Temperature control indicator.
     * Example: true
     * Implementer: If true, guest rooms or meeting facilities contain temperature control mechanisms, such as digital thermostats for constant temperature control.
     *
     * @var mixed $tempControlInd
     */
    private $tempControlInd = null;

    /**
     * Wind turbines used indicator.
     * Example: true
     * Implementer: If true, the property uses wind turbines.
     *
     * @var bool $windTurbineInd
     */
    private $windTurbineInd = null;

    /**
     * Renewable energy kilowatts amount.
     * Example: 677
     * Implementer: This is the amount of power generated by any sources of renewable energy at the hotel in kilowatts.
     *
     * @var int $energyGenerated
     */
    private $energyGenerated = null;

    /**
     * Energy star rating.
     * Example: 4.2
     * Implementer: This is the energy star rating of the property.
     *
     * @var string $energyStarRating
     */
    private $energyStarRating = null;

    /**
     * Power usage detail.
     *
     * @var \Recranet\OTA\EnvironmentalImpactType\EnergyAType\UsageAType[] $usage
     */
    private $usage = [
        
    ];

    /**
     * Energy program description.
     *
     * @var \Recranet\OTA\ParagraphType[] $programDescription
     */
    private $programDescription = [
        
    ];

    /**
     * Gets as efficientAppliancesInd
     *
     * Energy efficient appliances indicator.
     * Example: true
     * Implementer: If true, the property uses energy efficient appliances (e.g. dish washers, washing machines, dryers).
     *
     * @return bool
     */
    public function getEfficientAppliancesInd()
    {
        return $this->efficientAppliancesInd;
    }

    /**
     * Sets a new efficientAppliancesInd
     *
     * Energy efficient appliances indicator.
     * Example: true
     * Implementer: If true, the property uses energy efficient appliances (e.g. dish washers, washing machines, dryers).
     *
     * @param bool $efficientAppliancesInd
     * @return self
     */
    public function setEfficientAppliancesInd($efficientAppliancesInd)
    {
        $this->efficientAppliancesInd = $efficientAppliancesInd;
        return $this;
    }

    /**
     * Gets as efficientLightingInd
     *
     * Energy efficient lighting used indicator.
     * Example: true
     * Implementer: If true, the property uses energy saving lighting facilities, such as energy-efficient LED fixtures.
     *
     * @return bool
     */
    public function getEfficientLightingInd()
    {
        return $this->efficientLightingInd;
    }

    /**
     * Sets a new efficientLightingInd
     *
     * Energy efficient lighting used indicator.
     * Example: true
     * Implementer: If true, the property uses energy saving lighting facilities, such as energy-efficient LED fixtures.
     *
     * @param bool $efficientLightingInd
     * @return self
     */
    public function setEfficientLightingInd($efficientLightingInd)
    {
        $this->efficientLightingInd = $efficientLightingInd;
        return $this;
    }

    /**
     * Gets as heatPowerCombInd
     *
     * Combined heat and power units used indicator.
     * Example: true
     * Implementer: If true, the property uses combined heat and power units.
     *
     * @return bool
     */
    public function getHeatPowerCombInd()
    {
        return $this->heatPowerCombInd;
    }

    /**
     * Sets a new heatPowerCombInd
     *
     * Combined heat and power units used indicator.
     * Example: true
     * Implementer: If true, the property uses combined heat and power units.
     *
     * @param bool $heatPowerCombInd
     * @return self
     */
    public function setHeatPowerCombInd($heatPowerCombInd)
    {
        $this->heatPowerCombInd = $heatPowerCombInd;
        return $this;
    }

    /**
     * Gets as heatPumpInd
     *
     * Heat pumps used indicator.
     * Example: true
     * Implementer: If true, the property uses heat pumps.
     *
     * @return bool
     */
    public function getHeatPumpInd()
    {
        return $this->heatPumpInd;
    }

    /**
     * Sets a new heatPumpInd
     *
     * Heat pumps used indicator.
     * Example: true
     * Implementer: If true, the property uses heat pumps.
     *
     * @param bool $heatPumpInd
     * @return self
     */
    public function setHeatPumpInd($heatPumpInd)
    {
        $this->heatPumpInd = $heatPumpInd;
        return $this;
    }

    /**
     * Gets as powerSavingPolicyInd
     *
     * Power saving policy indicator.
     * Example: true
     * Implementer: If true, the property has a power saving policy.
     *
     * @return bool
     */
    public function getPowerSavingPolicyInd()
    {
        return $this->powerSavingPolicyInd;
    }

    /**
     * Sets a new powerSavingPolicyInd
     *
     * Power saving policy indicator.
     * Example: true
     * Implementer: If true, the property has a power saving policy.
     *
     * @param bool $powerSavingPolicyInd
     * @return self
     */
    public function setPowerSavingPolicyInd($powerSavingPolicyInd)
    {
        $this->powerSavingPolicyInd = $powerSavingPolicyInd;
        return $this;
    }

    /**
     * Gets as solarInd
     *
     * Solar energy used indicator.
     * Example: true
     * Implementer: If true, the property uses solar energy.
     *
     * @return bool
     */
    public function getSolarInd()
    {
        return $this->solarInd;
    }

    /**
     * Sets a new solarInd
     *
     * Solar energy used indicator.
     * Example: true
     * Implementer: If true, the property uses solar energy.
     *
     * @param bool $solarInd
     * @return self
     */
    public function setSolarInd($solarInd)
    {
        $this->solarInd = $solarInd;
        return $this;
    }

    /**
     * Gets as tempControlInd
     *
     * Temperature control indicator.
     * Example: true
     * Implementer: If true, guest rooms or meeting facilities contain temperature control mechanisms, such as digital thermostats for constant temperature control.
     *
     * @return mixed
     */
    public function getTempControlInd()
    {
        return $this->tempControlInd;
    }

    /**
     * Sets a new tempControlInd
     *
     * Temperature control indicator.
     * Example: true
     * Implementer: If true, guest rooms or meeting facilities contain temperature control mechanisms, such as digital thermostats for constant temperature control.
     *
     * @param mixed $tempControlInd
     * @return self
     */
    public function setTempControlInd($tempControlInd)
    {
        $this->tempControlInd = $tempControlInd;
        return $this;
    }

    /**
     * Gets as windTurbineInd
     *
     * Wind turbines used indicator.
     * Example: true
     * Implementer: If true, the property uses wind turbines.
     *
     * @return bool
     */
    public function getWindTurbineInd()
    {
        return $this->windTurbineInd;
    }

    /**
     * Sets a new windTurbineInd
     *
     * Wind turbines used indicator.
     * Example: true
     * Implementer: If true, the property uses wind turbines.
     *
     * @param bool $windTurbineInd
     * @return self
     */
    public function setWindTurbineInd($windTurbineInd)
    {
        $this->windTurbineInd = $windTurbineInd;
        return $this;
    }

    /**
     * Gets as energyGenerated
     *
     * Renewable energy kilowatts amount.
     * Example: 677
     * Implementer: This is the amount of power generated by any sources of renewable energy at the hotel in kilowatts.
     *
     * @return int
     */
    public function getEnergyGenerated()
    {
        return $this->energyGenerated;
    }

    /**
     * Sets a new energyGenerated
     *
     * Renewable energy kilowatts amount.
     * Example: 677
     * Implementer: This is the amount of power generated by any sources of renewable energy at the hotel in kilowatts.
     *
     * @param int $energyGenerated
     * @return self
     */
    public function setEnergyGenerated($energyGenerated)
    {
        $this->energyGenerated = $energyGenerated;
        return $this;
    }

    /**
     * Gets as energyStarRating
     *
     * Energy star rating.
     * Example: 4.2
     * Implementer: This is the energy star rating of the property.
     *
     * @return string
     */
    public function getEnergyStarRating()
    {
        return $this->energyStarRating;
    }

    /**
     * Sets a new energyStarRating
     *
     * Energy star rating.
     * Example: 4.2
     * Implementer: This is the energy star rating of the property.
     *
     * @param string $energyStarRating
     * @return self
     */
    public function setEnergyStarRating($energyStarRating)
    {
        $this->energyStarRating = $energyStarRating;
        return $this;
    }

    /**
     * Adds as usage
     *
     * Power usage detail.
     *
     * @return self
     * @param \Recranet\OTA\EnvironmentalImpactType\EnergyAType\UsageAType $usage
     */
    public function addToUsage(\Recranet\OTA\EnvironmentalImpactType\EnergyAType\UsageAType $usage)
    {
        $this->usage[] = $usage;
        return $this;
    }

    /**
     * isset usage
     *
     * Power usage detail.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetUsage($index)
    {
        return isset($this->usage[$index]);
    }

    /**
     * unset usage
     *
     * Power usage detail.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetUsage($index)
    {
        unset($this->usage[$index]);
    }

    /**
     * Gets as usage
     *
     * Power usage detail.
     *
     * @return \Recranet\OTA\EnvironmentalImpactType\EnergyAType\UsageAType[]
     */
    public function getUsage()
    {
        return $this->usage;
    }

    /**
     * Sets a new usage
     *
     * Power usage detail.
     *
     * @param \Recranet\OTA\EnvironmentalImpactType\EnergyAType\UsageAType[] $usage
     * @return self
     */
    public function setUsage(array $usage = null)
    {
        $this->usage = $usage;
        return $this;
    }

    /**
     * Adds as programDescription
     *
     * Energy program description.
     *
     * @return self
     * @param \Recranet\OTA\ParagraphType $programDescription
     */
    public function addToProgramDescription(\Recranet\OTA\ParagraphType $programDescription)
    {
        $this->programDescription[] = $programDescription;
        return $this;
    }

    /**
     * isset programDescription
     *
     * Energy program description.
     *
     * @param int|string $index
     * @return bool
     */
    public function issetProgramDescription($index)
    {
        return isset($this->programDescription[$index]);
    }

    /**
     * unset programDescription
     *
     * Energy program description.
     *
     * @param int|string $index
     * @return void
     */
    public function unsetProgramDescription($index)
    {
        unset($this->programDescription[$index]);
    }

    /**
     * Gets as programDescription
     *
     * Energy program description.
     *
     * @return \Recranet\OTA\ParagraphType[]
     */
    public function getProgramDescription()
    {
        return $this->programDescription;
    }

    /**
     * Sets a new programDescription
     *
     * Energy program description.
     *
     * @param \Recranet\OTA\ParagraphType[] $programDescription
     * @return self
     */
    public function setProgramDescription(array $programDescription = null)
    {
        $this->programDescription = $programDescription;
        return $this;
    }
}

