Recranet\OTA\EnvironmentalImpactType\RecyclingAType\DetailsAType:
    properties:
        recycledProducts:
            expose: true
            access_type: public_method
            serialized_name: RecycledProducts
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getRecycledProducts
                setter: setRecycledProducts
            xml_list:
                inline: true
                entry_name: RecycledProducts
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\ListRecycledProductsType>
        recyclingLocations:
            expose: true
            access_type: public_method
            serialized_name: RecyclingLocations
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getRecyclingLocations
                setter: setRecyclingLocations
            xml_list:
                inline: true
                entry_name: RecyclingLocations
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\ListRecycleFacilityLocationType>
