Recranet\OTA\EnvironmentalImpactType\RecyclingAType:
    properties:
        activeProgramInd:
            expose: true
            access_type: public_method
            serialized_name: ActiveProgramInd
            accessor:
                getter: getActiveProgramInd
                setter: setActiveProgramInd
            xml_attribute: true
            type: bool
        ecologicalDishwareInd:
            expose: true
            access_type: public_method
            serialized_name: EcologicalDishwareInd
            accessor:
                getter: getEcologicalDishwareInd
                setter: setEcologicalDishwareInd
            xml_attribute: true
            type: bool
        details:
            expose: true
            access_type: public_method
            serialized_name: Details
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getDetails
                setter: setDetails
            type: Recranet\OTA\EnvironmentalImpactType\RecyclingAType\DetailsAType
        programDescription:
            expose: true
            access_type: public_method
            serialized_name: ProgramDescription
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getProgramDescription
                setter: setProgramDescription
            xml_list:
                inline: true
                entry_name: ProgramDescription
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\ParagraphType>
