Recranet\OTA\Type\OTAHotelBookingRuleRS\OTAHotelBookingRuleRSAType\RuleMessageAType\StatusApplicationAType\RoomRatesAType\RoomRateAType:
    properties:
        currencyCode:
            expose: true
            access_type: public_method
            serialized_name: CurrencyCode
            accessor:
                getter: getCurrencyCode
                setter: setCurrencyCode
            xml_attribute: true
            type: string
        decimalPlaces:
            expose: true
            access_type: public_method
            serialized_name: DecimalPlaces
            accessor:
                getter: getDecimalPlaces
                setter: setDecimalPlaces
            xml_attribute: true
            type: int
        amount:
            expose: true
            access_type: public_method
            serialized_name: Amount
            accessor:
                getter: getAmount
                setter: setAmount
            xml_attribute: true
            type: float
        rateTimeUnit:
            expose: true
            access_type: public_method
            serialized_name: RateTimeUnit
            accessor:
                getter: getRateTimeUnit
                setter: setRateTimeUnit
            xml_attribute: true
            type: string
        unitMultiplier:
            expose: true
            access_type: public_method
            serialized_name: UnitMultiplier
            accessor:
                getter: getUnitMultiplier
                setter: setUnitMultiplier
            xml_attribute: true
            type: int
        start:
            expose: true
            access_type: public_method
            serialized_name: Start
            accessor:
                getter: getStart
                setter: setStart
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        duration:
            expose: true
            access_type: public_method
            serialized_name: Duration
            accessor:
                getter: getDuration
                setter: setDuration
            xml_attribute: true
            type: DateInterval
        end:
            expose: true
            access_type: public_method
            serialized_name: End
            accessor:
                getter: getEnd
                setter: setEnd
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        rateDescription:
            expose: true
            access_type: public_method
            serialized_name: RateDescription
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getRateDescription
                setter: setRateDescription
            type: Recranet\OTA\Type\ParagraphType
