Recranet\OTA\Type\OTAHotelBookingRuleRS\OTAHotelBookingRuleRSAType\RuleMessageAType\StatusApplicationAType\RoomRatesAType:
    properties:
        roomRate:
            expose: true
            access_type: public_method
            serialized_name: RoomRate
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getRoomRate
                setter: setRoomRate
            xml_list:
                inline: true
                entry_name: RoomRate
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\Type\OTAHotelBookingRuleRS\OTAHotelBookingRuleRSAType\RuleMessageAType\StatusApplicationAType\RoomRatesAType\RoomRateAType>
