Recranet\OTA\ProductDescriptionsType:
    properties:
        productDescription:
            expose: true
            access_type: public_method
            serialized_name: ProductDescription
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getProductDescription
                setter: setProductDescription
            xml_list:
                inline: true
                entry_name: ProductDescription
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\ProductDescriptionsType\ProductDescriptionAType>
