Recranet\OTA\StatisticApplicationSetType\StatisticCodesAType:
    properties:
        statisticCode:
            expose: true
            access_type: public_method
            serialized_name: StatisticCode
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getStatisticCode
                setter: setStatisticCode
            xml_list:
                inline: true
                entry_name: StatisticCode
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\StatisticApplicationSetType\StatisticCodesAType\StatisticCodeAType>
