Recranet\OTA\Type\StatisticApplicationSetType:
    properties:
        start:
            expose: true
            access_type: public_method
            serialized_name: Start
            accessor:
                getter: getStart
                setter: setStart
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        duration:
            expose: true
            access_type: public_method
            serialized_name: Duration
            accessor:
                getter: getDuration
                setter: setDuration
            xml_attribute: true
            type: DateInterval
        end:
            expose: true
            access_type: public_method
            serialized_name: End
            accessor:
                getter: getEnd
                setter: setEnd
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        statisticCodes:
            expose: true
            access_type: public_method
            serialized_name: StatisticCodes
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getStatisticCodes
                setter: setStatisticCodes
            type: array<Recranet\OTA\Type\StatisticApplicationSetType\StatisticCodesAType\StatisticCodeAType>
            xml_list:
                inline: false
                entry_name: StatisticCode
                skip_when_empty: true
                namespace: 'http://www.opentravel.org/OTA/2003/05'
        revenueCategorySummaries:
            expose: true
            access_type: public_method
            serialized_name: RevenueCategorySummaries
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getRevenueCategorySummaries
                setter: setRevenueCategorySummaries
            type: array<Recranet\OTA\Type\StatisticApplicationSetType\RevenueCategorySummariesAType\RevenueCategorySummaryAType>
            xml_list:
                inline: false
                entry_name: RevenueCategorySummary
                skip_when_empty: true
                namespace: 'http://www.opentravel.org/OTA/2003/05'
        countCategorySummaries:
            expose: true
            access_type: public_method
            serialized_name: CountCategorySummaries
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getCountCategorySummaries
                setter: setCountCategorySummaries
            type: array<Recranet\OTA\Type\StatisticApplicationSetType\CountCategorySummariesAType\CountCategorySummaryAType>
            xml_list:
                inline: false
                entry_name: CountCategorySummary
                skip_when_empty: true
                namespace: 'http://www.opentravel.org/OTA/2003/05'
        reportSummaries:
            expose: true
            access_type: public_method
            serialized_name: ReportSummaries
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getReportSummaries
                setter: setReportSummaries
            type: array<Recranet\OTA\Type\ParagraphType>
            xml_list:
                inline: false
                entry_name: ReportSummary
                skip_when_empty: true
                namespace: 'http://www.opentravel.org/OTA/2003/05'
