Recranet\OTA\Type\StatisticType\StatisticApplicationSetsAType:
    properties:
        statisticApplicationSet:
            expose: true
            access_type: public_method
            serialized_name: StatisticApplicationSet
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getStatisticApplicationSet
                setter: setStatisticApplicationSet
            xml_list:
                inline: true
                entry_name: StatisticApplicationSet
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\Type\StatisticApplicationSetType>
