Recranet\OTA\Type\StatusApplicationControlType:
    properties:
        start:
            expose: true
            access_type: public_method
            serialized_name: Start
            accessor:
                getter: getStart
                setter: setStart
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        duration:
            expose: true
            access_type: public_method
            serialized_name: Duration
            accessor:
                getter: getDuration
                setter: setDuration
            xml_attribute: true
            type: DateInterval
        end:
            expose: true
            access_type: public_method
            serialized_name: End
            accessor:
                getter: getEnd
                setter: setEnd
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\Date
        ratePlanType:
            expose: true
            access_type: public_method
            serialized_name: RatePlanType
            accessor:
                getter: getRatePlanType
                setter: setRatePlanType
            xml_attribute: true
            type: string
        ratePlanCode:
            expose: true
            access_type: public_method
            serialized_name: RatePlanCode
            accessor:
                getter: getRatePlanCode
                setter: setRatePlanCode
            xml_attribute: true
            type: string
        ratePlanID:
            expose: true
            access_type: public_method
            serialized_name: RatePlanID
            accessor:
                getter: getRatePlanID
                setter: setRatePlanID
            xml_attribute: true
            type: string
        ratePlanQualifier:
            expose: true
            access_type: public_method
            serialized_name: RatePlanQualifier
            accessor:
                getter: getRatePlanQualifier
                setter: setRatePlanQualifier
            xml_attribute: true
            type: bool
        promotionCode:
            expose: true
            access_type: public_method
            serialized_name: PromotionCode
            accessor:
                getter: getPromotionCode
                setter: setPromotionCode
            xml_attribute: true
            type: string
        promotionVendorCode:
            expose: true
            access_type: public_method
            serialized_name: PromotionVendorCode
            accessor:
                getter: getPromotionVendorCode
                setter: setPromotionVendorCode
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\Jms\SimpleListOf<string>
        ratePlanCategory:
            expose: true
            access_type: public_method
            serialized_name: RatePlanCategory
            accessor:
                getter: getRatePlanCategory
                setter: setRatePlanCategory
            xml_attribute: true
            type: string
        invCodeApplication:
            expose: true
            access_type: public_method
            serialized_name: InvCodeApplication
            accessor:
                getter: getInvCodeApplication
                setter: setInvCodeApplication
            xml_attribute: true
            type: string
        invCode:
            expose: true
            access_type: public_method
            serialized_name: InvCode
            accessor:
                getter: getInvCode
                setter: setInvCode
            xml_attribute: true
            type: string
        invType:
            expose: true
            access_type: public_method
            serialized_name: InvType
            accessor:
                getter: getInvType
                setter: setInvType
            xml_attribute: true
            type: string
        invTypeCode:
            expose: true
            access_type: public_method
            serialized_name: InvTypeCode
            accessor:
                getter: getInvTypeCode
                setter: setInvTypeCode
            xml_attribute: true
            type: string
        isRoom:
            expose: true
            access_type: public_method
            serialized_name: IsRoom
            accessor:
                getter: getIsRoom
                setter: setIsRoom
            xml_attribute: true
            type: bool
        mon:
            expose: true
            access_type: public_method
            serialized_name: Mon
            accessor:
                getter: getMon
                setter: setMon
            xml_attribute: true
            type: bool
        tue:
            expose: true
            access_type: public_method
            serialized_name: Tue
            accessor:
                getter: getTue
                setter: setTue
            xml_attribute: true
            type: bool
        weds:
            expose: true
            access_type: public_method
            serialized_name: Weds
            accessor:
                getter: getWeds
                setter: setWeds
            xml_attribute: true
            type: bool
        thur:
            expose: true
            access_type: public_method
            serialized_name: Thur
            accessor:
                getter: getThur
                setter: setThur
            xml_attribute: true
            type: bool
        fri:
            expose: true
            access_type: public_method
            serialized_name: Fri
            accessor:
                getter: getFri
                setter: setFri
            xml_attribute: true
            type: bool
        sat:
            expose: true
            access_type: public_method
            serialized_name: Sat
            accessor:
                getter: getSat
                setter: setSat
            xml_attribute: true
            type: bool
        sun:
            expose: true
            access_type: public_method
            serialized_name: Sun
            accessor:
                getter: getSun
                setter: setSun
            xml_attribute: true
            type: bool
        ratePlanCodeType:
            expose: true
            access_type: public_method
            serialized_name: RatePlanCodeType
            accessor:
                getter: getRatePlanCodeType
                setter: setRatePlanCodeType
            xml_attribute: true
            type: string
        rateTier:
            expose: true
            access_type: public_method
            serialized_name: RateTier
            accessor:
                getter: getRateTier
                setter: setRateTier
            xml_attribute: true
            type: string
        allRateCode:
            expose: true
            access_type: public_method
            serialized_name: AllRateCode
            accessor:
                getter: getAllRateCode
                setter: setAllRateCode
            xml_attribute: true
            type: bool
        allInvCode:
            expose: true
            access_type: public_method
            serialized_name: AllInvCode
            accessor:
                getter: getAllInvCode
                setter: setAllInvCode
            xml_attribute: true
            type: bool
        invBlockCodeApply:
            expose: true
            access_type: public_method
            serialized_name: InvBlockCodeApply
            accessor:
                getter: getInvBlockCodeApply
                setter: setInvBlockCodeApply
            xml_attribute: true
            type: string
        invBlockCode:
            expose: true
            access_type: public_method
            serialized_name: InvBlockCode
            accessor:
                getter: getInvBlockCode
                setter: setInvBlockCode
            xml_attribute: true
            type: string
        override:
            expose: true
            access_type: public_method
            serialized_name: Override
            accessor:
                getter: getOverride
                setter: setOverride
            xml_attribute: true
            type: bool
        quoteID:
            expose: true
            access_type: public_method
            serialized_name: QuoteID
            accessor:
                getter: getQuoteID
                setter: setQuoteID
            xml_attribute: true
            type: string
        subBlockCode:
            expose: true
            access_type: public_method
            serialized_name: SubBlockCode
            accessor:
                getter: getSubBlockCode
                setter: setSubBlockCode
            xml_attribute: true
            type: string
        wingIdentifier:
            expose: true
            access_type: public_method
            serialized_name: WingIdentifier
            accessor:
                getter: getWingIdentifier
                setter: setWingIdentifier
            xml_attribute: true
            type: string
        destinationSystemCodes:
            expose: true
            access_type: public_method
            serialized_name: DestinationSystemCodes
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getDestinationSystemCodes
                setter: setDestinationSystemCodes
            type: array<string>
            xml_list:
                inline: false
                entry_name: DestinationSystemCode
                skip_when_empty: true
                namespace: 'http://www.opentravel.org/OTA/2003/05'
