Recranet\OTA\StatisticApplicationSetType\ReportSummariesAType:
    properties:
        reportSummary:
            expose: true
            access_type: public_method
            serialized_name: ReportSummary
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getReportSummary
                setter: setReportSummary
            xml_list:
                inline: true
                entry_name: ReportSummary
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\ParagraphType>
