Recranet\OTA\StatisticApplicationSetType\RevenueCategorySummariesAType:
    properties:
        revenueCategorySummary:
            expose: true
            access_type: public_method
            serialized_name: RevenueCategorySummary
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getRevenueCategorySummary
                setter: setRevenueCategorySummary
            xml_list:
                inline: true
                entry_name: RevenueCategorySummary
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\StatisticApplicationSetType\RevenueCategorySummariesAType\RevenueCategorySummaryAType>
