Recranet\OTA\StatisticApplicationSetType\CountCategorySummariesAType:
    properties:
        countCategorySummary:
            expose: true
            access_type: public_method
            serialized_name: CountCategorySummary
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getCountCategorySummary
                setter: setCountCategorySummary
            xml_list:
                inline: true
                entry_name: CountCategorySummary
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            type: array<Recranet\OTA\StatisticApplicationSetType\CountCategorySummariesAType\CountCategorySummaryAType>
