Recranet\OTA\Type\TrainSegmentType:
    properties:
        departureDateTime:
            expose: true
            access_type: public_method
            serialized_name: DepartureDateTime
            accessor:
                getter: getDepartureDateTime
                setter: setDepartureDateTime
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        arrivalDateTime:
            expose: true
            access_type: public_method
            serialized_name: ArrivalDateTime
            accessor:
                getter: getArrivalDateTime
                setter: setArrivalDateTime
            xml_attribute: true
            type: GoetasWebservices\Xsd\XsdToPhp\XMLSchema\DateTime
        stopQuantity:
            expose: true
            access_type: public_method
            serialized_name: StopQuantity
            accessor:
                getter: getStopQuantity
                setter: setStopQuantity
            xml_attribute: true
            type: int
        journeyDuration:
            expose: true
            access_type: public_method
            serialized_name: JourneyDuration
            accessor:
                getter: getJourneyDuration
                setter: setJourneyDuration
            xml_attribute: true
            type: DateInterval
        crossBorderInd:
            expose: true
            access_type: public_method
            serialized_name: CrossBorderInd
            accessor:
                getter: getCrossBorderInd
                setter: setCrossBorderInd
            xml_attribute: true
            type: bool
        departureStation:
            expose: true
            access_type: public_method
            serialized_name: DepartureStation
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getDepartureStation
                setter: setDepartureStation
            type: Recranet\OTA\Type\StationDetailsType
        arrivalStation:
            expose: true
            access_type: public_method
            serialized_name: ArrivalStation
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getArrivalStation
                setter: setArrivalStation
            type: Recranet\OTA\Type\StationDetailsType
        marketingCompany:
            expose: true
            access_type: public_method
            serialized_name: MarketingCompany
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getMarketingCompany
                setter: setMarketingCompany
            type: Recranet\OTA\Type\CompanyNameType
        operatingCompany:
            expose: true
            access_type: public_method
            serialized_name: OperatingCompany
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getOperatingCompany
                setter: setOperatingCompany
            type: Recranet\OTA\Type\CompanyNameType
        equipment:
            expose: true
            access_type: public_method
            serialized_name: Equipment
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getEquipment
                setter: setEquipment
            type: Recranet\OTA\Type\ClassCodeType
        trainInfo:
            expose: true
            access_type: public_method
            serialized_name: TrainInfo
            xml_element:
                namespace: 'http://www.opentravel.org/OTA/2003/05'
            accessor:
                getter: getTrainInfo
                setter: setTrainInfo
            type: Recranet\OTA\Type\TrainInfoType
